[theme]
primaryColor = "#0867D9"
backgroundColor = "#F3F7FC"
secondaryBackgroundColor = "#EEF4FC"
textColor = "#102B55"
font = "sans serif"

[server]
headless = true

[client]
toolbarMode = "minimal"
