[theme]
primaryColor = "#08776A"
backgroundColor = "#F3F6F8"
secondaryBackgroundColor = "#EDF3F5"
textColor = "#172F3D"
font = "sans serif"

[server]
headless = true

[client]
toolbarMode = "minimal"
