[theme]
primaryColor = "#006B57"
backgroundColor = "#F8FAF8"
secondaryBackgroundColor = "#EEF5F1"
textColor = "#192B35"
font = "sans serif"

[server]
headless = true
enableStaticServing = true

[client]
toolbarMode = "minimal"
